import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout.js";
import styles from "../styles/Home.module.css";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import moment, * as moments from "moment";
import Link from 'next/link'

export default function Home({posts}) {
  return (
    <Layout>
      <Head>
        <title>Fernando's Blog</title>
        <meta name="description" content="Generated by create next apSlifep" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Banner */}
      <section id="banner" className="major">
        <div className="inner">
          <header className="major">
            <h1>Hi, my name is Forty</h1>
          </header>
          <div className="content">
            <p>
              A responsive site template designed by HTML5 UP
              <br />
              and released under the Creative Commons.
            </p>
            <ul className="actions">
              <li>
                <Link href="#one" className="button next scrolly">
                  Get Started
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </section>
      {/* Main */}
      <div id="main">
        {/* One */}
        <section id="one" className="tiles">

        {/* Loop over posts */}

        {posts.map((post) => (
                  <article>
                    <span className="image">
                      <img src={`/assets/images/${post.featured_image}`} alt="" />
                    </span>
                    <header className="major">
                      <h3>
                        <Link href={`/${post.slug}`} className="link">
                          {post.title}
                        </Link>
                      </h3>
                      <p>Ipsum dolor sit amet</p>
                    </header>
                  </article>))}
        </section>
        {/* Two */}
        <section id="two">
          <div className="inner">
            <header className="major">
              <h2>Massa libero</h2>
            </header>
            <p>
              Nullam et orci eu lorem consequat tincidunt vivamus et sagittis
              libero. Mauris aliquet magna magna sed nunc rhoncus pharetra.
              Pellentesque condimentum sem. In efficitur ligula tate urna.
              Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor.
              Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis
              libero. Mauris aliquet magna magna sed nunc rhoncus amet pharetra
              et feugiat tempus.
            </p>
            <ul className="actions">
              <li>
                <Link href="landing.html" className="button next">
                  Get Started
                </Link>
              </li>
            </ul>
          </div>
        </section>
      </div>
    </Layout>
  );
}

export const getStaticProps = async () => {
  const sortPosts = () => {
    const allPosts = fs.readdirSync("posts").map((filename) => {
      const file = fs.readFileSync(path.join("posts", filename)).toString();
      const postData = matter(file);

      return {
        slug: postData.data.slug,
        title: postData.data.title,
        featured_image: postData.data.featured_image,
        date: postData.data.date,
        slug: postData.data.slug
      };
    });
    console.log(allPosts);
    return allPosts.sort(
      (a, b) =>
        new moment(b.date).format("YYYY-MM-DD HH:mm:ss") -
        new moment(a.date).format("YYYY-MM-DD HH:mm:ss")
    );
  };
  console.log(fs.readdirSync("posts"));


  return {
    props: {
      posts: sortPosts(),
    },
  };
};
